# Generated by Django 4.2.6 on 2024-02-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
